# Generated by Django 5.2.7 on 2025-10-05 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认标签')),
            ],
        ),
        migrations.CreateModel(
            name='PointSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_points', models.PositiveIntegerField(verbose_name='初始积分')),
                ('remaining_points', models.PositiveIntegerField(verbose_name='剩余积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='获得时间')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='过期时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_sources', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='point_sources', to='points.tag', verbose_name='标签')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='变动积分')),
                ('transaction_type', models.CharField(choices=[('EARN', '获得'), ('SPEND', '消费')], max_length=10)),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('consumed_sources', models.ManyToManyField(related_name='consuming_transactions', to='points.pointsource')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
