# Generated by Django 5.2.7 on 2025-10-06 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_add_slug_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointsource',
            options={'ordering': ['created_at'], 'verbose_name': '积分来源', 'verbose_name_plural': '积分来源'},
        ),
        migrations.AlterModelOptions(
            name='pointtransaction',
            options={'ordering': ['-created_at'], 'verbose_name': '积分交易记录', 'verbose_name_plural': '积分交易记录'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '积分标签', 'verbose_name_plural': '积分标签'},
        ),
    ]
