# Generated by Django 5.2.7 on 2025-10-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_alter_pointsource_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointsource',
            options={'ordering': ['created_at'], 'verbose_name': '积分池', 'verbose_name_plural': '积分池'},
        ),
    ]
