# Generated by Django 5.2.7 on 2025-10-25 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_tag_withdrawable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('EARN', '获得'), ('SPEND', '消费'), ('WITHDRAW', '提现')], max_length=10),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(verbose_name='提现积分数量')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], db_index=True, default='PENDING', max_length=20, verbose_name='状态')),
                ('real_name', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('id_number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('phone_number', models.CharField(max_length=11, verbose_name='手机号')),
                ('bank_name', models.CharField(max_length=100, verbose_name='开户银行')),
                ('bank_account', models.CharField(max_length=50, verbose_name='银行账号')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理员备注')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('point_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='points.pointsource', verbose_name='积分来源')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '提现申请',
                'verbose_name_plural': '提现申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
