# Generated by Django 5.2.7 on 2025-11-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_alter_pointtransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsource',
            name='allow_recharge',
            field=models.BooleanField(default=False, verbose_name='允许充值'),
        ),
    ]
