# Generated by Django 5.2.7 on 2025-11-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0011_pointsource_allow_recharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='allow_recharge',
            field=models.BooleanField(default=False, verbose_name='允许充值'),
        ),
    ]
