# Generated by Django 5.2.7 on 2025-10-05 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="个人简介"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="生日"),
                ),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub 地址")),
                ("homepage_url", models.URLField(blank=True, verbose_name="个人主页")),
                ("blog_url", models.URLField(blank=True, verbose_name="博客地址")),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="Twitter 地址"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="LinkedIn 地址"),
                ),
                (
                    "company",
                    models.CharField(blank=True, max_length=100, verbose_name="公司"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="位置"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(max_length=100, verbose_name="学校/机构名称"),
                ),
                (
                    "degree",
                    models.CharField(blank=True, max_length=50, verbose_name="学位"),
                ),
                (
                    "field_of_study",
                    models.CharField(max_length=100, verbose_name="专业领域"),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="accounts.userprofile",
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习经历",
                "verbose_name_plural": "学习经历",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名称"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="职位")),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                ("description", models.TextField(blank=True, verbose_name="工作描述")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="accounts.userprofile",
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作经历",
                "verbose_name_plural": "工作经历",
                "ordering": ["-start_date"],
            },
        ),
    ]
