# Generated by Django 5.2.7 on 2025-11-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organization_organizationmembership_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='accounts_or_provide_00b03a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='provider_login',
        ),
    ]
