# Generated by Django 5.2.7 on 2025-11-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_organization_accounts_or_provide_00b03a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='organization',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/avatars/', verbose_name='头像'),
        ),
    ]
