# Generated by Django 5.2.9 on 2026-07-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_drop_user_email_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_country_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='OpenDigger country tag ID, e.g. :divisions/CN', max_length=50, verbose_name='Location country ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location_subdivision_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='OpenDigger subdivision tag ID, e.g. :divisions/CN/CN-BJ', max_length=50, verbose_name='Location subdivision ID'),
        ),
    ]
