# Generated by Django 5.2.9 on 2026-07-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_userprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location_city_name',
            field=models.CharField(blank=True, default='', help_text='City name from OpenDigger subdivision cities, stored as name_zh', max_length=100, verbose_name='Location city name'),
        ),
    ]
