# Generated by Django 5.2.9 on 2026-07-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_location_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_completion_rewarded',
            field=models.BooleanField(default=False, help_text='Whether the user has claimed the profile completion reward', verbose_name='Profile completion rewarded'),
        ),
    ]
