# Generated by Django 5.2.7 on 2025-10-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='image',
            field=models.FileField(blank=True, help_text='商品展示图片', null=True, upload_to='shop/items/', verbose_name='商品图片'),
        ),
    ]
