# Generated by Django 5.2.9 on 2026-07-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_reach', '0002_bilingual_content_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachcampaign',
            name='cities',
            field=models.JSONField(default=list),
        ),
    ]
