# Generated by Django 5.2.7 on 2025-10-25 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容(Markdown)')),
                ('message_type', models.CharField(choices=[('system', '系统消息'), ('personal', '个人消息'), ('payment', '支付信息'), ('shipping', '发货信息'), ('activity', '活动通知'), ('announcement', '公告'), ('points', '积分变动'), ('order', '订单信息'), ('security', '安全提醒'), ('withdrawal', '提现信息')], default='system', max_length=20, verbose_name='消息类型')),
                ('is_broadcast', models.BooleanField(default=False, help_text='是否发送给全站用户', verbose_name='广播消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sender', models.ForeignKey(blank=True, help_text='留空表示系统消息', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='用户端软删除', verbose_name='已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='site_messages.message', verbose_name='消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户消息',
                'verbose_name_plural': '用户消息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='site_messag_created_17c060_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='site_messag_message_72c26e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_broadcast'], name='site_messag_is_broa_c51ff5_idx'),
        ),
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['user', '-created_at'], name='site_messag_user_id_537675_idx'),
        ),
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['user', 'is_read'], name='site_messag_user_id_a23efb_idx'),
        ),
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['user', 'is_deleted'], name='site_messag_user_id_96c610_idx'),
        ),
        migrations.AddIndex(
            model_name='usermessage',
            index=models.Index(fields=['message', 'is_read'], name='site_messag_message_68f30e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermessage',
            unique_together={('user', 'message')},
        ),
    ]
